### ISSUE TITLE
Validation not working on i18n props on Jahia 8.1.7.x

### ISSUE THREAD

**Issue by baptistegrimaud** [Jahia/html-filtering#125]
### Environment and versions used

Following https://github.com/Jahia/html-filtering/issues/120#issuecomment-2938737673.
The GraphQL validation endpoint does not see the i18n properties and therefore the validation is not correct.
The problem is fixed in Jahia 8.2.x

### Steps to reproduce

1. Use Jahia 8.1.7.x
2. Install HTML Filtering module latest version
3. Create a site
4. Configure that site with a `REJECT` strategy for the `editWorkspace` by creating an OSGi configuration file `META-INF/configurations/org.jahia.modules.htmlfiltering.site-<yoursite>.yml`, example:
```yml
htmlFiltering:
  editWorkspace:
    strategy: REJECT
    process: ['nt:base.*']
    allowedRuleSet:
      elements:
        - attributes: [id]
        - tags: [p]
  liveWorkspace:
    strategy: REJECT
    process: ['nt:base.*']
    allowedRuleSet:
      elements:
        - attributes: [id]
        - tags: [p]

```
5. Create or update a i18n RichText property of that site with a content that should be rejected with an error, example:
```html
<script>not allowed</script>
```

### Current Behavior

No error occurs, the property gets updated with the new value

### Desired Behavior

The validation should throw an error and prevent the property to be updated with that disallowed tag
