### ISSUE TITLE
Allow HTML Filtering to have different rules

### ISSUE THREAD

**Issue by GauBen** [Jahia/html-filtering#66]
> [!IMPORTANT]
> - [ ] Before working on this issue, ensure it follows our [Definition of Ready](https://jahia-confluence.atlassian.net/wiki/spaces/PR/pages/2064566/Definition+of+Ready+-+Ref+ISPOL08.A140180)

Allow HTML Filtering to have different rules for:

-    Per site - already covered
-    Different workspaces: default workspace and live + Skip sanitization / validation for publications + import

-    Add automated tests for everything

-   Per nodeType

Example of conf after story 2 and 3:

```yaml
htmlFiltering:
  strategy:
    - sanityze
  workspace:
   - default
  protocols:
    - http
    - https
  nodeTypes:
    - jnt:content
  attributes:
    <lotOfStuff>
```

> [!IMPORTANT]
> - [ ] Before closing this issue, ensure it follows our [Definition of Done](https://jahia-confluence.atlassian.net/wiki/spaces/PR/pages/2072202/Definition+of+Done+-+Ref+ISPOL08.A14030)
