### ISSUE TITLE
Create 2 pages on jahia academy on security and XSS injection/HTML filtering

### ISSUE THREAD

**Issue by GauBen** [Jahia/html-filtering#69]
- Security on Jahia CMS (with links to csrf, security filter, html filtering, csp) - To be done by Benji and Gautier
  - Include a section on how to migrate from old to new version, if particular manipulations are needed.
  - Detail/explain import/export with HTML filtering (going through the rules during these operations - @jkevan 's input during one of the daily)
- XSS injection and HTML Filtering

Once the page is published, remove the [repos's readme](https://github.com/Jahia/html-filtering/blob/main/README.md) to point to that new page.

In the known limitations, we should mention that if the selector type is set via json override, then the filtering won't apply.

**Comment by GauBen** [comment]
@romain-pm @bpapez Where should this page live on the academy?

**Comment by jkevan** [comment]
# HTML Filtering V2.0.0 Module for Jahia

## Overview

The HTML Filtering module provides XSS (Cross-Site Scripting) filtering protection in Jahia when contributing contents that have properties containing HTML markup. It helps ensure that user-generated HTML content is safe and free from potentially malicious code.

The module doesn't have to be enabled on a site to work and start filtering HTML. As soon as the module is installed and started, it will be applied and fully working based on the global default configuration that is installed with it.

## Configuration

### Configuration Files and Priority

The module can be configured at three different levels, with a clear priority order:

1. **Site-specific configuration** (highest priority)
   - Filename: `org.jahia.modules.htmlfiltering.site-SITE_KEY.yml`
   - Purpose: Create separate configuration for a specific site
   - Example: `org.jahia.modules.htmlfiltering.site-digitall.yml`

2. **Global custom configuration** (medium priority)
   - Filename: `org.jahia.modules.htmlfiltering.global.custom.yml`
   - Purpose: Override default settings for all Jahia sites
   - Managed by administrators to customize HTML filtering rules

3. **Global default configuration** (lowest priority)
   - Filename: `org.jahia.modules.htmlfiltering.global.default.yml`
   - Purpose: Provide minimal recommended configuration
   - Installed automatically by the module
   - Not recommended to modify as it will be reinstalled with each module update

If a configuration file is invalid or contains incorrect values, it will not be loaded, and the system will fall back to the next configuration in the priority chain. Error logs will indicate which configuration was not loaded and why.

### Configuration Structure

All configuration files follow the same structure, with separate sections for different workspaces. Here's an example of a configuration file:

```yaml
# Configuration file structure
htmlFiltering:
  formatDefinitions:
    HTML_ID: '[a-zA-Z0-9\:\-_\.]+'
    NUMBER_OR_PERCENT: '\d+%?'
    LINKS_URL: '(?:(?:[\p{L}\p{N}\\\.#@$%\+&;\-_~,\?=/!{}:]+|#(\w)+)|(\s*(?:(?:ht|f)tps?://|mailto:)[\p{L}\p{N}][\p{L}\p{N}\p{Zs}\.#@$%\+&:\-_~,\?=/!\(\)]*+\s*))'
  editWorkspace:
    strategy: REJECT
    skipOnPermissions: []
    process: ['nt:base.*']
    skip: []
    allowedRuleSet:
      elements:
        # Rules for allowed elements and attributes
      protocols: [http, https, mailto]
  liveWorkspace:
    strategy: SANITIZE
    skipOnPermissions: []
    process: ['nt:base.*']
    skip: []
    allowedRuleSet:
      elements:
        # Rules for allowed elements and attributes
      protocols: [http, https, mailto]
```

### Configuration Components

#### Format Definitions

The `formatDefinitions` section contains regular expression patterns that can be reused in rules:

```yaml
formatDefinitions:
  HTML_ID: '[a-zA-Z0-9\:\-_\.]+'
  NUMBER_OR_PERCENT: '\d+%?'
  LINKS_URL: '(?:(?:[\p{L}\p{N}\\\.#@$%\+&;\-_~,\?=/!{}:]+|#(\w)+)|(\s*(?:(?:ht|f)tps?://|mailto:)[\p{L}\p{N}][\p{L}\p{N}\p{Zs}\.#@$%\+&:\-_~,\?=/!\(\)]*+\s*))'
```

These patterns can be referenced in the rules to enforce specific formats for attribute values.

#### Workspace Configuration

The module provides separate sections for each Jahia workspace within the same configuration file:

- **editWorkspace**: Configuration section for the default workspace (used for content editing)
- **liveWorkspace**: Configuration section for the live workspace (used for direct content creation on the live workspace)

Having separate sections allows for different levels of protection based on the context. The live workspace often requires stricter rules since it may include content created by users with fewer privileges (e.g., blog posts, forum comments).

#### Strategy

The `strategy` setting defines how the module handles HTML content with potentially unsafe elements:

- **SANITIZE**: Automatically removes invalid markup when content is saved
  - Advantage: Doesn't block saving, cleans content automatically
  - Jahia recommended strategy for live workspace where direct feedback may not be available

- **REJECT**: Validates content when saved and rejects the save operation if invalid markup is found
  - Returns constraint violations listing all invalid tags
  - Requires the user to manually fix the content before saving
  - Jahia recommended strategy for default workspace where content creators have access to advanced editing UI

#### Process and Skip Settings

These settings define which node types and properties should be processed or skipped by the HTML filtering:

- **process**: Defines node types and properties to be processed
  - Example: `process: ['nt:base.*']` applies filtering to all properties of all node types
  
- **skip**: Defines node types and properties to be excluded from filtering
  - Example: `skip: ['nt:myNodeType.*']` skips filtering for all properties of a specific node type
  - Example: `skip: ['nt:myNodeType.myProperty']` skips filtering for a specific property

The `skip` setting takes precedence over the `process` setting.

**Note**: The node type and property notation doesn't necessarily follow a strict nodetype-property relation. For example, if a node is of type `jnt:bigText` and has an additional mixin `jmix:htmlReadme` (which contains property `j:htmlContent`), then a configuration like `skip: ['jnt:bigText.j:htmlContent']` is valid. It will skip processing of `j:htmlContent` when set on a `jnt:bigText` node, even if there's no direct relation between them.

#### Skip on Permissions

The `skipOnPermissions` setting allows you to specify permissions that, when granted to a user, will cause HTML filtering to be bypassed:

```yaml
skipOnPermissions: ['view-full-wysiwyg-editor', 'site-admin']
```

This is useful when certain privileged users need to include HTML markup that would normally be filtered out. For example:

- `view-full-wysiwyg-editor`: Users with access to the full WYSIWYG rich text editor experience could be granted the power to bypass HTML filtering
- `site-admin`: Site administrators might need to include specific HTML elements for site functionality

It's important to note that Jahia does not recommend any default permissions for this setting to keep content safe regardless of privilege level. It's up to each implementation to determine whether to use this feature and which permissions to include.

**Note**: Using `skipOnPermissions` can create inconsistent content editor experiences. If a privileged user creates HTML content with markup that would normally be filtered, less privileged users attempting to edit that same content later may not be able to save their changes. This happens because the HTML filtering will be applied to their edits, causing the save operation to fail if the existing content contains elements not allowed for their permission level.

#### Rule Sets

The `allowedRuleSet` and `disallowedRuleSet` sections define which HTML elements and attributes are permitted or prohibited:

```yaml
allowedRuleSet:
  elements:
    - attributes: [class, dir, hidden, lang, role, style, title]
    - attributes:
        - id
      format: HTML_ID
    - attributes: [align]
      tags: [caption, col, colgroup, hr, img, table, tbody, td, tfoot, th, thead, tr]
    # More element rules...
  protocols: [http, https, mailto]
```

Each rule can specify:
- **tags**: Which HTML tags the rule applies to
- **attributes**: Which attributes are allowed for those tags
- **format**: A reference to a format definition that the attribute value must match

The `protocols` section defines which URL protocols are allowed in attributes like `href` and `src`.

**Note**: The `allowedRuleSet` is mandatory and should contain at least one rule, while `disallowedRuleSet` is optional.

## GraphQL API

The module exposes a GraphQL API for validating and sanitizing HTML content:

```graphql
query HtmlFiltering($html: String!, $workspace: Workspace = EDIT, $siteKey: String) {
    htmlFiltering {
        validate(html: $html, workspace: $workspace, siteKey: $siteKey) {
            removedTags
            removedAttributes {
                attributes
                tag
            }
            sanitizedHtml
            safe
        }
    }
}
```

This API can be used to validate or sanitize HTML strings, with the appropriate configuration selected based on the specified workspace and site key.

The API returns the following fields:

- **removedTags**: A list of tags that were removed during the sanitization process
- **removedAttributes**: A list of removed attributes along with the tags they were removed from
- **sanitizedHtml**: A sanitized version of the input HTML markup based on the underlying configuration
- **safe**: A boolean value that returns `true` if nothing was removed from the input HTML markup and it's valid according to the configuration that was used

## Usage

For a property to be processed by HTML filtering, the following conditions must be met:

1. The current user doesn't have any permission defined in the `skipOnPermissions` configuration
2. The property matches at least one pattern in the `process` configuration
3. The property doesn't match any pattern in the `skip` configuration
4. The property is defined as a RichText property in the Content Definition File (.cnd)

Example of property definitions in a .cnd file:

```
[nt:myNodeType] > jnt:content, jmix:droppableContent
    - myHTMLProperty (string, richtext)
    - willNotProcessed (string)
```

In this example, `myHTMLProperty` will be processed by HTML filtering because it has the `richtext` constraint, while `willNotProcessed` will not be processed because it lacks this constraint.

### JSON Overrides and HTML Filtering

jContent supports .cnd overrides (called JSON overrides) which allow you to override the .cnd constraints. For example, JSON Overrides can override property constraints to use a different field type when editing content in Jahia jContent edition UI.

It's important to note that HTML filtering is not able to process these JSON overrides, so they will be ignored by the filtering system. For example, consider a .cnd:

```
[nt:myNodeType] > jnt:content, jmix:droppableContent
    - willNotProcessed (string)
```

coupled with a JSON Override:

```json
{
  "nodeType": "nt:myNodeType",
  "sections": [
    {
      "name": "content",
      "fieldSets": [       
            {
              "rank": 1.2,
              "name": "willNotProcessed",
              "selectorType": "RichText"
            }
          ]
        }
      ]
    }
  ]
}
```

This configuration will have no effect on HTML filtering. jContent will display a WYSIWYG field for your property, allowing you to contribute HTML markup, but HTML filtering will simply ignore this property because it's not declared as `richtext` in the .cnd definition.

## Best Practices

1. **Don't modify the global default configuration file**
   - Create a custom global configuration or site-specific configuration instead

2. **Be careful with skipOnPermissions**
   - Only grant HTML filtering bypass permissions to trusted users
   - Be aware of the potential inconsistent editing experience it may create

3. **Monitor for rejected content saves**
   - Educate content creators about allowed HTML elements and attributes
   - Consider expanding the allowed elements if legitimate use cases arise

4. **Always declare HTML properties with the richtext constraint in .cnd**
   - Remember that JSON overrides do not affect HTML filtering
   - To protect all properties that can contain HTML markup, they must be declared using the RichText selector type in .cnd

5. **Check server logs when adding or editing configurations**
   - Verify that your configuration has been properly loaded
   - Some configuration properties are mandatory and subject to validation
   - If a configuration is invalid, it will not be loaded, and HTML filtering will fall back to another configuration in the priority chain

## Breaking changes, migrating from v1.x

TODO

## Conclusion

The HTML Filtering module provides robust XSS protection for Jahia sites while offering flexible configuration options. By properly configuring the module according to your security requirements, you can protect your site from malicious content while still allowing legitimate HTML markup.
