### ISSUE TITLE
Support multiple node types

### ISSUE THREAD

**Issue by baptistegrimaud** [Jahia/html-filtering#74]
Not just nt:base

**Comment by baptistegrimaud** [comment]
Update: it is possible to tell at runtime if a property of a given node is declared with the "richtext" selector using:
```java
SelectorType.RICHTEXT == ((ExtendedPropertyDefinition)node.getProperty("myProp").getDefinition()).getSelector()
```

So we want to hardcode this filter in replacement of the filtering on the String type of the properties?
Or should we make it configurable at the node type level, for instance:
```yml
htmlFiltering:
  editWorkspace:
    nodeTypes:
      - "jnt:bigText":
          - selectors:
            - "RICHTEXT"
            - "TEXTAREA"
```

A most advanced version could even support regex, and avec selectors targeted on properties:
```yml
htmlFiltering:
  editWorkspace:
    nodeTypes:
      - "jnt:*":
         - properties:
           - "j:*"
             - selectors:
               - "RICHTEXT"
               - "TEXTAREA"
```
Thoughts?

**Comment by baptistegrimaud** [comment]
Only process String properties with the RichText selector.

Then, we can define the node types / properties 
```yaml
htmlFiltering:
  editWorkspace:
     include: ["nt:base.*", "myNode.*",  "myNode.myProp"] # not regex, just '*' meaning all properties
     exclude: ["nt:base.*", "myNode.*"] # always takes precedence over the include
    allowedRuleSet:
      elements:
        - attributes: [class, dir, hidden, lang, role, style, title]
        - ...
```

default one:
```yaml
htmlFiltering:
  editWorkspace:
     strategy: REJECT # strict validation. To be confirmed?
     include: ["nt:base.*"] # means all properties of the nt:base
     exclude: []
  liveWorkspace:
     strategy: SANITIZE
     include: ["nt:base:*"]
     exclude: []
```

**Comment by GauBen** [comment]
Names of things:

- Nodes/props that will be processed: `process: ['nt:base']`
- Nodes/props that will be ignored: `skip: ['nt:base.modifiedAt']`

**Comment by baptistegrimaud** [comment]
Additional details about the changes:
- each workspace (`editWorkspace` and `liveWorkspace`) now accept 2 additional parameters (`process` and `skip`) to restrict on which properties of which node types the sanitization/validation should happen
- both parameters take an array of strings, each element representing properties of nodes that should be included (if listed in the `process` parameter) or excluded (if listed in the `skip` parameter)
- each item of those arrays should have the following format: `<nodeType>[.*|.<propertyName>]`. The wildcard `*` means all properties. Example of valid values:
  - `nt:base`: to target all nodes (and that's the base type for all primary node types)
  - `nt:base.*`: (same result as above)
  - `mynt:mynode.myProperty`: (a property named `myProperty` on all nodes of type `mynt:mynode` **or a subtype of it**)
- `process` is mandatory and a non-empty array must be provided
- `skip` is optional and by default an empty array is used
- the _fallback_ configuration (to be soon renamed _default_ in https://github.com/Jahia/html-filtering/pull/94) processes by default all properties of all nodes as it is shipped with the following settings (for both edit and live workspaces):
```yml
   ...
   process: ['nt:base.*']
   skip: []
   ...
```
- the values listed in `skip` take precedence over the ones listed in `process` and are meant to exclude some specific properties that might have been included with the `process` parameter. To evaluate if a given property of a given node type should be filtered by sanitization or validation (depending on the selected strategy), the module first checks if it's a String property with a Rich Text selector, then check if the property for that given node type matches an entry of `process`, and finally check that it does not match an entry of `skip`.
- some Cypress tests have been added as part of this change and contains some concrete examples of what to expect for a given configuration in place. See [this test for details](https://github.com/Jahia/html-filtering/blob/main/tests/cypress/e2e/nodeTypesAndSelectors.cy.ts#L11)
