### ISSUE TITLE
Force explicit declaration of properties in the configuration

### ISSUE THREAD

**Issue by baptistegrimaud** [Jahia/html-filtering#90]
Ensure all the mandatory settings are defined in the configuration files and reject them (exception + ignore conf) if that's not the case.
There shouldn't be any default value for the configuration (`strategy`, `allowedRuleSet`.`elements`, etc.).
Special case for the empty collections that could be `null` / not defined: `disallowedRuleSet`

What's mandatory:
```yml
# default configuration
htmlFiltering:
  editWorkspace:
    strategy: ...
    allowedRuleSet:
      elements: ...
  liveWorkspace:
    strategy: ...
    allowedRuleSet:
      elements: ...
```
